GET http://localhost:3000/employees

###

GET http://localhost:3000/employees/6203c815c86ff8cd63f38efd

###

POST http://localhost:3000/employees
Content-Type: application/json

{
    "Name": "Cosmin Sturzu",
    "Adress": "Bucuresti, Sectorul 6, Strada A, Blocul 12F",
    "Email": "cosmins@gmail.com",
    "Hire_date": "05.05.2021",
    "Salary": 5000,
    "Job_title": "Full Stack Developer"
}

###

DELETE http://localhost:3000/employees/6203cb55aa190bc324d25aad


###

PATCH http://localhost:3000/employees/6203c815c86ff8cd63f38efd
Content-Type: application/json

{
    "Name": "Uwuya"
}

