GET http://localhost:3000/employees

###

GET http://localhost:3000/employees/6203c808f9eed28f3966cc31

###

POST http://localhost:3000/employees
Content-Type: application/json

{
    "Name": "Teebss",
    "Adress": "B",
    "Email": "email@gmail.com",
    "Hire_date": "02.02.2022",
    "Salary": 111,
    "Job_title": "FSD"
}

###

DELETE http://localhost:3000/employees/6203c8de56f85dc188fbb31d


###

PATCH http://localhost:3000/employees/6203c815c86ff8cd63f38efd
Content-Type: application/json

{
    "Name": "New Name"
}

